name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up uv cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          # Install both main and dev dependencies
          uv pip install -e .
          uv pip install ruff==0.3.4 mypy>=1.13.0,<2 pytest>=8.3.4,<9 types-requests>=2.32.0,<3.0.0 types-beautifulsoup4>=4.12.0,<5.0.0

      - name: Debug environment
        run: |
          source .venv/bin/activate
          echo "Python version:"
          python --version
          echo "Installed packages:"
          pip list
          echo "Virtual env bin directory contents:"
          ls -la .venv/bin/

      - name: Check formatting
        run: |
          source .venv/bin/activate
          python -m ruff format --check .

      - name: Run linting
        run: |
          source .venv/bin/activate
          python -m ruff check .

      - name: Run type checking
        run: |
          source .venv/bin/activate
          python -m mypy .

  test:
    name: Tests
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up uv cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          # Install both main and dev dependencies
          uv pip install -e .
          uv pip install pytest>=8.3.4,<9

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest tests/
